# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
      include: scope
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: all
