# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: CD

on:
  release:
    types: [created]

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml

  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/step-security/harden-runner
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit

      # https://github.com/pypa/gh-action-pypi-publish
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@c7f29f7adef1a245bd91520e94867e5c6eedddcc # v1.6.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
