name: Update pre-commit hooks

permissions:
  contents: read

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@0b496e91ec7ae4428c3ed2eeb4c3a40df431f2cc # v1.1.0

      # TODO
      - name: Update pre-commit hooks
        uses: vrslev/pre-commit-autoupdate@f1be719f7afea8e3b9b4a899a7a3bc834e76079b # v1.0.0
        with:
          extra-args: --freeze

      # TODO: switch to creyD/prettier_action
      - name: Prettify code
        uses: actionsx/prettier@v2
        with:
          args: --write .pre-commit-config.yaml

      - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: pre-commit-autoupdate
          title: "chore(deps): update pre-commit hooks"
          commit-message: "chore(deps): update pre-commit hooks"
          body: Update pre-commit hooks
          labels: |
            dependencies
            pre-commit
          delete-branch: true
