# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Update pre-commit hooks

permissions:
  contents: read

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  update:
    # permissions:
    #   contents: write
    #   pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # https://github.com/step-security/harden-runner
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      # https://github.com/vrslev/pre-commit-autoupdate
      - name: Update pre-commit hooks
        uses: vrslev/pre-commit-autoupdate@f1be719f7afea8e3b9b4a899a7a3bc834e76079b # v1.0.0
        with:
          extra-args: --freeze

      # https://github.com/actionsx/prettier#usage
      - name: Prettify code
        uses: actionsx/prettier@8b6d14bd1241e743fa9a6112b43d691d1890a8e9 # v2
        with:
          args: --write .pre-commit-config.yaml

      # https://github.com/peter-evans/create-pull-request
      - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        # https://github.com/peter-evans/create-pull-request/issues/48
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: main
          branch: pre-commit-autoupdate
          title: "chore(deps-dev): update pre-commit hooks"
          commit-message: "chore(deps-dev): update pre-commit hooks"
          body: Update pre-commit hooks
          labels: |
            dependencies
            pre-commit
          delete-branch: true
