# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Publish

on:
  release:
    types: [created]

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/step-security/harden-runner
      - name: Harden Runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          egress-policy: audit

      - name: Check out the repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies with poetry
        run: poetry install --no-interaction --verbose --with=docs

      - name: Deploy the documentation
        run: poetry run mkdocs gh-deploy --strict --verbose

      - name: Build the Python package
        run: poetry build --ansi

      # https://github.com/pypa/gh-action-pypi-publish
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@c7f29f7adef1a245bd91520e94867e5c6eedddcc # v1.6.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
