name: "Stale"

on:
  schedule:
    # run once a month at midnight of the first day of the month
    - cron: 0 0 1 * *

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Close stale Issues
        uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed if no further activity occurs. Thank you for your contributions.
          days-before-stale: 90
          days-before-close: 30
          stale-issue-label: "status:stale"
          stale-pr-label: "status:stale"
